### ISSUE TITLE
httd() doesn't notice changes

### ISSUE THREAD

**Issue by hadley** [yihui/servr#19]
I'm not sure how to debug this, but when I run `httd("md")` and modify a file, nothing happens.

**Comment by yihui** [comment]
httd() is a purely static server, and it does not watch the directory for changes or compile anything. Perhaps you can drop a Makefile under the directory, and call `servr::make()`, e.g. https://github.com/yihui/servr/blob/master/inst/examples/make2/Makefile

**Comment by hadley** [comment]
Oh nice, that's exactly what I was looking for! (Already had a make file)
