### ISSUE TITLE
rmdv1/2 not detecting file changes when using RStudio server

### ISSUE THREAD

**Issue by noamross** [yihui/servr#20]
I've started using servr for viewing live-updates to Rmd files in the RStudio preview pane while I edit.  This works fine when I'm running on natively on OSX, but when I'm running RStudio Server via the browser there's no live update.  It appears servr is not detecting file changes - the HTML is not re-compiled when I save an Rmd.  

I've tried this running the RStudio Server on both on my own Ubuntu box and  on the rocker/rstudio-daily:verse Docker image.

**Comment by yihui** [comment]
Thanks! Should be fixed now.
