### ISSUE TITLE
fail to autogenerate .md file

### ISSUE THREAD

**Issue by karagawa** [yihui/servr#22]
Hi, yihui:

I want to report that servr::jekyll() can't auto-generate .md file here. I followed your suggestion that put .rmd file into an independent folder "_resource"， but servr cannot autogenerate any .rmd files in that folder. However, if I move the .rmd file into the root folder, it works. Please let me know if you have any idea of what happen here. Thanks!

P.S., I actually using servr::jekyll(command = "bundle exec jekyll build");   servr::jekyll() does not work here.

**Comment by yihui** [comment]
I guess I was talking about `_source` instead of `_resource`. Did I have a typo somewhere?

If you want to use `_resource` anyway, you have to reflect it in the `input` argument of `jekyll()`.

**Comment by karagawa** [comment]
Oops! It works now. Thank you very much. Apologies for my carelessness!
