### ISSUE TITLE
servr::rmdv2(daemon=TRUE) crash in windows

### ISSUE THREAD

**Issue by ctguxp** [yihui/servr#23]
Hi,
When I used servr::rmdv2(daemon=TRUE) command in Rstudio on Windows, It always made R session crashed after running 3 minitus. It display as "R Session Aborted. Rencoutered a fatal error. The session was teminnated." Please check this issues, Thanks.

**Comment by yihui** [comment]
Thanks for the report, but I guess I'm unlikely to have the time to investigate this issue...

**Comment by yihui** [comment]
The last time I tried it and I remember I did have certain issues, but today I tried again with the latest preview release of RStudio, and I didn't see problems anymore: https://www.rstudio.com/products/rstudio/download/preview/

**Comment by yihui** [comment]
`install.packages("later")` should fix it with **servr** v0.8.
