### ISSUE TITLE
jekyll() needs custom baseurl on rstudio server

### ISSUE THREAD

**Issue by itcarroll** [yihui/servr#32]
When trying to use `jekyll()` on RStudio Server, absolute paths relative to the base URL do not work.

When I run `jekyll()`, the site is served at "http://localhost:4321" and becomes (automagically) reachable at "http://my.rstudio.server/p/4321/". But since my `_layouts/default.html`, has `<link rel="stylesheet" href="/assets/css/custom.css"/>`, which is as it should be for hosting on GitHub pages (for example), the stylesheet cannot be found.

Somehow, the base url needs to include `/p/4321/` on RStudio Server, right?

**Comment by yihui** [comment]
This is essentially the same issue as https://github.com/rstudio/blogdown/issues/124, to which I don't really have a general solution.

**Comment by itcarroll** [comment]
Ah, too bad.

Well, here's my workaround for anyone finding this later:

1) Drop to the terminal and execute `bundle exec jekyll build --watch --baseurl /p/4321`
2) On R console, run `servr::httw('_site', port = 4321)`.

This way jekyll inserts the "/p/4321" wherever you have `{{ site.baseurl }}` and `httw` doesn't add it to the actual url served. Seems to get me automatic site regeneration and page refresh on file changes. Now I just need to go through my site and insert `{{ site.baseurl }}` all over the place (which I should probably have already done anyway).

**Comment by yihui** [comment]
That is a clever workaround! Yeah, the key is that your theme must respect `site.baseurl` everywhere. If I can make this assumption to all Jekyll/Hugo themes, this problem will be much easier to solve, but apparently not all theme authors make use this variable consistently. That is the single challenge for me to solve this problem.
