### ISSUE TITLE
installation error (Mutex creation failed) on manjaro/arch linux

### ISSUE THREAD

**Issue by sje30** [yihui/servr#36]
```
install.packages('servr', repos = 'https://xran.yihui.name')  # devel version
Installing package into ‘/home/stephen/NOBACKUP/RLIB’
(as ‘lib’ is unspecified)
trying URL 'https://xran.yihui.name/src/contrib/servr_0.11.2.tar.gz'
Content type 'application/gzip' length 20692 bytes (20 KB)
==================================================
downloaded 20 KB

* installing *source* package ‘servr’ ...
** R
** inst
** byte-compile and prepare package for lazy loading
terminate called after throwing an instance of 'std::runtime_error'
  what():  Mutex creation failed
/usr/lib64/R/bin/INSTALL: line 34: 11429 Done                    echo 'tools:::.install_packages()'
     11430 Aborted                 (core dumped) | R_DEFAULT_PACKAGES= LC_COLLATE=C "${R_HOME}/bin/R" $myArgs --slave --args ${args}

The downloaded source packages are in
	‘/tmp/Rtmpc9duFK/downloaded_packages’
Warning message:
In install.packages("servr", repos = "https://xran.yihui.name") :
  installation of package ‘servr’ had non-zero exit status
```
This seems to a problem on arch linux (which Is what I'm using, or rather manjaro):

https://github.com/RcppCore/RcppParallel/issues/77

and would indicate a short-term solution is to downgrade glibc, but is that the right thing for long-term?

**Comment by yihui** [comment]
I don't even have an idea what this error means...

**Comment by sje30** [comment]
me neither, but I thought I'd share it in case others hit it too.

https://bugs.archlinux.org/task/59581 seems to note that it is because code (presumably R here) does not yet support linking with glibc 2.28

**Comment by sje30** [comment]
The CRAN version of the later package, which is used during installation, is broken for
arch.  The solution is to install later from github:

remotes::install_github('r-lib/later')
