### ISSUE TITLE
nginx and initpath and baseurl, oh my

### ISSUE THREAD

**Issue by itcarroll** [yihui/servr#37]
I don't know if you can help @yihui, but can't hurt to ask? I'm sorry I cannot think how to provide you a MWE...

I have RStudio Server running behind nginx proxy, so the url after logging in is "https://www.xyz.org/rstudio/"

I have a static site that I want to show in the RStudio viewer, so I proceed thusly:

```
> servr::httd('.', initpath = 'course', baseurl = '/rstudio')
To stop the server, run servr::daemon_stop(1) or restart your R session
Serving the directory /path/to/files at http://127.0.0.1:4321/rstudio/course
```

Well, okay, that looks not quite right. What's going to happen in the viewer? Oh ...

```
Not found:
./rstudio/course
```

But the site is working outside the viewer. I can open a tab and navigate to "https://www.xyz.org/rstudio/p/4321/course/" and the page is just as expected. How can I get it in the viewer?

**Comment by yihui** [comment]
Is it really necessary to set `baseurl` in `httd()`?

**Comment by itcarroll** [comment]
Turns out not, and I just figured out the rest of the problem. Chrome knew to add a trailing "/" to my URL while the Viewer did not. So the solution is simply:

```
> servr::httd('.', initpath = 'course/')
```

For any who come here in the future, with nginx + Jekyll problems, note that the `--baseurl=/rstudio/p/4321` flag (which I did mention above) remains needed.
