### ISSUE TITLE
URLs on RStudio Server

### ISSUE THREAD

**Issue by itcarroll** [yihui/servr#38]
I know this isn't likely a "servr" issue, but I'm encountering it through `servr::httd` and I did not get any help from the [rstudio community](https://community.rstudio.com/t/new-url-for-locally-served-content-which-used-to-be-at-p-port).

From RStudio Server, it used to be the case that a site launched through `servr::httd(..., port = 1234)` was available from my server session at "https://rstudio.example.org/p/1234". It's not anymore (since RStudio 1.2?); it's now at "https://rstudio.example.org/p/xyzpdq". Is there some way to control or at least capture that path through the "port" argument?

**Comment by yihui** [comment]
I replied to your post in RStudio Community. Thanks!
