### ISSUE TITLE
"auto_ptr" deprecation warning on installation

### ISSUE THREAD

**Issue by cooknl** [yihui/servr#43]
I'm new to Ubuntu (from Win10). 
I've got an existing bookdown project that I'm trying to work on from my Ubuntu machine.

platform: x86_64-pc-linux-gnu
Ubuntu 20.04 LTS

Prior to installing servr, the following were installed:

r-base 3.6.3-2
rstudio:amd64 1.2.5042
tinytex 0.22
bookdown 0.18

The version of servr is:
servr 0.16

During the install, done from inside an R session with install.packages("servr"), it took a long time and there were many many deprecation warnings about "auto_ptr"

It did eventually install.

**Comment by yihui** [comment]
Would you please post the full log? **servr** is a pure R package that does not contain C++ code, so it's very unlikely that it is the culprit.

**Comment by cooknl** [comment]
I will try.

**Comment by cooknl** [comment]
I could not find the logs.

**Comment by yihui** [comment]
Thanks anyway!
