### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by statquant** [yihui/servr#63]
Hello,
My understanding is that there is no way to open a server with a password. Would that be a feature you would consider adding ? 
Maybe you know of an alternative package that allows to do this ?
Many thanks for all your cool work

**Comment by yihui** [comment]
This could be implemented (and should be easy to implement), but if you are providing a public-facing web service that needs authentication, I wouldn't recommend using **servr**. I'm not an expert in web servers and the **servr** package doesn't provide any security warranty. You should use it only for yourself or people who you trust.

**Comment by statquant** [comment]
Hello, this is well understood, anyway no solution is perfectly secured, and this would be fine for 99.99% of users. This would be used within a set of people within the same organisation. That would really be great for us.

**Comment by yihui** [comment]
Okay, now that you understand it, you can install the development version:

```r
remotes::install_github('yihui/servr')
```

and see `?servr::server_config` for an example of using the `auth` argument for authentication. Thanks!

**Comment by statquant** [comment]
This works great, thank you very much

**Comment by yihui** [comment]
You are welcome!
