### ISSUE TITLE
Support for bundle in jekyll

### ISSUE THREAD

**Issue by blindjesse** [yihui/servr#7]
I am requesting the addition of a `use_bundle=TRUE` or similar option for the `jekyll` function, to run eg `bundle exec jekyll build` instead of just `jekyll build`

**Comment by yihui** [comment]
Sounds like a good idea and easy to implement. Pull request welcome :) I prefer `bundle = FALSE` by default.

**Comment by blindjesse** [comment]
Ok, I just issued a pull request. Also looks like the docs were updated when I rebuilt them with roxygen2 4.1.0. Let me know if there are problems with this...go easy, it's my first fork and pull :)

**Comment by yihui** [comment]
Sorry, on second thought, I changed the interface since I guess my approach is more general: now you call `servr::jekyll(command = 'bundle exec jekyll build')`. It is a little longer, but brings the possibility for other people to use different commands. Thanks!
